apiVersion: v1
kind: Service
metadata:
  name: payload-processor
spec:
  selector:
    app: payload-processor
  ports:
    - protocol: TCP
      port: 9004
      targetPort: 9004
      appProtocol: HTTP2
  type: ClusterIP
